### ISSUE TITLE
mongodb full text search

### ISSUE THREAD

**Issue by adnanmokhtar** [pimlie/laravel-datatables-mongodb#2]
How to use full text search with this plugin ?

**Comment by pimlie** [comment]
What do you mean exactly, can you describe it a bit more? Eg do you mean just searching on any columns or specifically use a mongodb text index?

**Comment by adnanmokhtar** [comment]
Yes i mean mongodb text index.

**Comment by pimlie** [comment]
You will have to use the filter column api in which you add a custom keyword search. See: https://yajrabox.com/docs/laravel-datatables/master/filter-column

and use something like (please check the laravel-mongodb repo for more examples)
```php
$query->whereRaw(array('$text' => array('$search' => $keyword)));
```
